AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'bin/*'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false
